version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"  # Viteの開発サーバー
      - "9229:9229"  # デバッグポート
    command: npm run debug
